version: '2'
services:
  elasticsearch:
    image: "elasticsearch:2.4.4"
    container_name: elasticsearch
    ports:
     - "9200:9200"
  kibana:
    image: "kibana:4.6.4"
    container_name: kibana
    ports:
     - "5601:5601"
    environment:
            -  ELASTICSEARCH_URL=http://elasticsearch:9200
