version: '2'
services:
  elasticsearch:
    image: "elasticsearch:2.4.4"
    ports:
     - "9200:9200"
  kibana:
    image: "kibana:4.6.4"
    ports:
     - "5601:5601"
    environment:
            -  ELASTICSEARCH_URL=http://episode1_elasticsearch_1:9200
