path.home: config

filebeat.prospectors:

- input_type: log

  #json.keys_under_root: true

  paths:
    - application.log

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]

logging.level: debug
